---
kind: pipeline
name: Sonar Quality Scan

steps:
  - name: Setup Sonar.properties
    image: alpine
    commands:
      - "echo sonar.branch.name=${DRONE_COMMIT_BRANCH} >> sonar-project.properties"
      - "echo sonar.exclusions=vendor/** >> sonar-project.properties"
      - "echo sonar.php.coverage.reportPaths=_reports/logs/clover.xml >> sonar-project.properties"
      - "echo sonar.php.tests.reportPath=_reports/logs/phpunit.xml >> sonar-project.properties"

  - name: Run PHP Unit
    image: athaller/phpunit
    detach: false
    commands:
      - ./vendor/bin/phpunit

  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token

trigger:
  event:
    exclude:
      - pull_request
  branch:
    exclude:
      - ""


